# LOGGING CONFIGURATION:
logging.level.root: trace

# LOCAL H2 DATABASE CONFIGURATION:
#spring:
#  datasource:
#    driverClassName: org.h2.Driver
#    url: jdbc:h2:mem:todo
#    username: sa
#    password:
#  jpa:
#    database: h2
#    database-platform: org.hibernate.dialect.H2Dialect
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true


# LOCAL POSTGRESQL DATABASE CONFIGURATION:
spring:
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/todo
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
#  security:
#    user:
#      name: hieu
#      password: hieu